hydra:
  run:
    dir: 'train_experiment/${now:%Y-%m-%d}/${now:%H-%M}'
  output_subdir: 'yamls'

env:
  with_gpu: false
  display_every: 100

scene:
  filepath: "/Users/wiktorlazarski/Desktop/my_project/nerf-study/data/tiny_nerf_data.npz"
  chunksize: 16384
  near_thresh: 2.0
  far_thresh: 6.0

model:
  hidden_dim: 128
  num_encoding_functions: 6

training:
  lr: 0.005
  num_iters: 1000
  depth_samples_per_ray: 32
  test_every_n_iterations: 500