hydra:
  run:
    dir: 'train_experiment/${now:%Y-%m-%d}/${now:%H-%M}'
  output_subdir: 'yamls'

env:
  with_gpu: true
  wandb_project_name: nerf-study
  wandb_run_name: test-run2

scene:
  filepath: "path/to/nerf-study/data/tiny_nerf_data.npz"
  chunksize: 16384
  near_thresh: 2.0
  far_thresh: 6.0

model:
  hidden_dim: 128
  num_encoding_functions: 6

training:
  model: "model.ckpt"
  lr: 0.0003
  num_epochs: 10001
  depth_samples_per_ray: 128
  train_log_every_n_step: 50
  test_every_n_iterations: 50
